name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare Firebase credentials
      run: |
        cat << 'EOF' > serviceAccountKey.json
        ${{ secrets.FIREBASE_CREDENTIALS }}
        EOF

    - name: Copy code to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.BOT_HOST }}
        username: ${{ secrets.BOT_SSH_USER }}
        key: ${{ secrets.BOT_SSH_KEY }}
        port: ${{ secrets.BOT_SSH_PORT || 22 }}
        source: "."
        target: "~/giftbot"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.BOT_HOST }}
        username: ${{ secrets.BOT_SSH_USER }}
        key: ${{ secrets.BOT_SSH_KEY }}
        port: ${{ secrets.BOT_SSH_PORT || 22 }}
        script: |
          cd ~/giftbot

          # Build an image
          docker build -t giftbot:latest .

          # Remove previous container if any
          docker rm -f giftbot || true

          # Start a new with auto restart
          docker run -d \
            --name giftbot \
            --restart unless-stopped \
            -v /var/log/giftbot:/app/logs \
            -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e FIREBASE_CREDENTIALS=/app/serviceAccountKey.json \
            -e FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
            -e SYSLOG_HOST=host.docker.internal \
            -e SYSLOG_PORT=514 \
            giftbot:latest