name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Prepare Firebase credentials
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > serviceAccountKey.json

      # 1) Копируем весь репозиторий на сервер в папку ~/giftbot
      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.BOT_HOST }}
          username: ${{ secrets.BOT_SSH_USER }}
          key: ${{ secrets.BOT_SSH_KEY }}
          port: ${{ secrets.BOT_SSH_PORT || 22 }}
          source: "."
          target: "~/giftbot"

      # 2) По SSH переходим в ~/giftbot и собираем/запускаем контейнер
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BOT_HOST }}
          username: ${{ secrets.BOT_SSH_USER }}
          key: ${{ secrets.BOT_SSH_KEY }}
          script: |
            cd ~/giftbot

            # Собираем образ (Dockerfile должен быть здесь)
            docker build -t giftbot .

            # Останавливаем / удаляем старый контейнер, если есть
            docker stop giftbot || true
            docker rm   giftbot || true

            # Запускаем новый контейнер
            docker run -d \
              --restart unless-stopped \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e FIREBASE_CREDENTIALS=/app/serviceAccountKey.json \
              -e FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
              --name giftbot giftbot
